services:
  phoenix-sso-api:
    image: rjyspl/phoenix-sso-api:latest
    container_name: phoenix-sso-api

    environment:
      - TZ=Asia/Kolkata
      - BASIC_API_KEY=<YOUR_BASIC_API_KEY>
      - MAILBOX_API_KEY=<YOUR_MAILBOX_API_KEY>
      - ALLOWED_ORIGINS=<YOUR_ALLOWED_ORIGINS>,<YOUR_ALLOWED_ORIGINS_2>
      - COOKIE_DOMAIN=.<YOUR_DOMAIN>

      # Logging and Runtime
      - ENABLE_LOGGING=True
      - RUST_LOG=rust_api=TRACE
      - API_WORKERS_COUNT=4

      # PostgreSQL Database
      - POSTGRES_DB_URL=postgres://user:pass@0.0.0.0:1234/dbname?sslmode=require
      - PG_POOL_MAX_SIZE=20
      - PG_CONN_TIMEOUT=10
      - PG_POOL_WAIT_TIMEOUT=30
      - PG_POOL_NEW_CONNECTION_TIMEOUT=5
      - PG_POOL_RECYCLE_TIMEOUT=1800
      - PG_POOL_WARM_POOL=True
      - PG_POOL_WARM_POOL_SIZE=20
      - PG_SSL_ACCEPT_INVALID_CERTS=False
      - PG_SSL_ACCEPT_INVALID_HOSTNAMES=False
      - PG_SSL_ROOT_CERT_PATH=/ca.crt

      # Redis Cache
      - REDIS_URL=redis://:CatsAreAwesome@sso-cache:6379

      # RMQ Message Queue
      - RABBITMQ_DOMAIN=<YOUR_RABBITMQ_DOMAIN>
      - RABBITMQ_USER_NAME=<YOUR_RABBITMQ_USER_NAME>
      - RABBITMQ_PASSWORD=<YOUR_RABBITMQ_PASSWORD>
      - RABBITMQ_VIRTUAL_HOST=<YOUR_RABBITMQ_VIRTUAL_HOST>
      - RABBITMQ_EXCHANGE_NAME=amq.default
      - RABBITMQ_ROUTING_KEY=<YOUR_RABBITMQ_ROUTING_KEY>

    volumes:
      - /etc/phoenix-tls/ca.crt:/ca.crt:ro

    ports:
      - "127.0.0.1:8086:8686"

    networks:
      - sso-network

    restart: always

networks:
  sso-network:
    external: true
